---

  - name: Installing Prometheus for (Ubuntu)
    apt: 
      name: prometheus
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: Install PRometheus for (CentOS)
    dnf:
      name:
       - epel-release
       - snapd
      state: latest
      use_backend: dnf4
    when: ansible_distribution == "CentOS"

  - name: Enabling snapd (CentOS)
    command: systemctl enable --now snapd
    when: ansible_distribution == "CentOS"

  - name: Restart snapd (CentOS)
    command: systemctl restart snapd
    when: ansible_distribution == "CentOS"

  - name: Prometheus for CentOS
    command: snap install prometheus --classic
    when: ansible_distribution == "CentOS"
